version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: innoshop_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innoshop-network

  identity-api:
    image: identity-api
    build:
      context: .
      dockerfile: InnoShop.Identity.Api/Dockerfile
    container_name: innoshop_identity
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=InnoShop_Identity;Username=admin;Password=admin
      - ProductsApiUrl=http://products-api:8080
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - postgres
    networks:
      - innoshop-network

  products-api:
    image: products-api
    build:
      context: .
      dockerfile: InnoShop.Products.Api/Dockerfile
    container_name: innoshop_products
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=InnoShop_Products;Username=admin;Password=admin
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - postgres
    networks:
      - innoshop-network

volumes:
  postgres_data:

networks:
  innoshop-network:
    driver: bridge